# Generated by Django 5.0.1 on 2025-05-01 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugs', '0003_remove_drugs_dar_alter_drugs_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('once_day', 'Once a day'), ('twice_day', 'Twice a day'), ('thrice_day', 'Thrice a day'), ('every_6_hours', 'Every 6 hours'), ('custom', 'Custom(Enter bellow)')], max_length=20)),
                ('custom_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('timing', models.TextField(choices=[('before_meal', 'Before meal'), ('after_meal', 'After meal'), ('with_meal', 'With meal'), ('empty_stomach', 'On empty stomach'), ('custom', 'Custom(Enter bellow)')], max_length=20)),
                ('custom_timing', models.TextField(blank=True, max_length=20, null=True)),
                ('instruction', models.TextField(max_length=20)),
                ('drugs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drugs.drugs')),
            ],
        ),
    ]
