# Generated by Django 5.0.1 on 2025-05-01 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
        ('precription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='precription.prescription'),
        ),
    ]
