# Generated by Django 5.0.1 on 2025-05-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_medication_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='drugs',
            field=models.CharField(max_length=50),
        ),
    ]
