# Generated by Django 5.0.1 on 2025-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_alter_medication_drugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='custom_frequency',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='custom_timing',
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='timing',
            field=models.TextField(max_length=20),
        ),
    ]
