# Generated by Django 5.0.1 on 2025-05-04 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentsession',
            old_name='appointment_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='appointmentsession',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
