# Generated by Django 5.0.1 on 2025-05-04 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_rename_appointment_time_appointmentsession_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
