# Generated by Django 5.0.1 on 2025-05-04 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_remove_appointmentsession_doctor_and_more'),
        ('doctor', '0006_alter_doctor_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsession',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointmentsession',
            name='doctor',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
            preserve_default=False,
        ),
    ]
