# Generated by Django 5.0.1 on 2025-05-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_remove_appointmentsession_doctor_and_more'),
        ('doctor', '0006_alter_doctor_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentsession',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointmentsession',
            name='doctor',
            field=models.ManyToManyField(to='doctor.doctor'),
        ),
    ]
