# Generated by Django 5.0.1 on 2025-05-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_remove_appointmentsession_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentsession',
            options={'ordering': ['appointment_date', 'start_time']},
        ),
    ]
