# Generated by Django 5.0.1 on 2025-05-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_appointmentsession_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_appointment',
            name='serial_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
