# Generated by Django 5.0.1 on 2025-05-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_patient_appointment_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_appointment',
            name='status',
            field=models.TextField(choices=[('Seen', 'Seen'), ('Queue', 'Queue'), ('Running', 'Running'), ('Missing', 'Missing')], default='Queue', max_length=10),
        ),
    ]
