# Generated by Django 5.0.1 on 2025-05-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_patient_appointment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient_appointment',
            unique_together=set(),
        ),
    ]
