# Generated by Django 5.0.1 on 2025-05-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_alter_patient_appointment_unique_together'),
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient_appointment',
            unique_together={('patient', 'session')},
        ),
    ]
