# Generated by Django 5.0.1 on 2025-05-13 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_alter_patient_appointment_unique_together'),
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patient.patient'),
        ),
    ]
