# Generated by Django 5.0.1 on 2025-05-13 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_alter_patient_appointment_patient'),
        ('doctor', '0008_remove_doctor_degrees_alter_doctor_qualification'),
        ('patient', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsession',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='patient_appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient.patient'),
        ),
    ]
