# Generated by Django 5.0.1 on 2025-05-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_alter_appointmentsession_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_appointment',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient_appointment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
