# Generated by Django 5.0.1 on 2025-05-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_patient_appointment_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
