# Generated by Django 5.0.1 on 2025-05-31 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_alter_patient_appointment_diagnosis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentsession',
            options={'ordering': ['doctor', 'appointment_date', 'start_time']},
        ),
    ]
