# Generated by Django 5.0.1 on 2025-06-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_alter_appointmentsession_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient_appointment',
            options={'ordering': ['session', 'serial_no']},
        ),
        migrations.AlterUniqueTogether(
            name='patient_appointment',
            unique_together=set(),
        ),
    ]
