# Generated by Django 5.0.1 on 2025-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_bg_after_patient_bg_before_patient_bp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'N')], max_length=6),
        ),
    ]
