# Generated by Django 5.0.1 on 2025-06-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
