# Generated by Django 5.0.1 on 2025-06-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_patient_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='label',
            field=models.CharField(default='Other', max_length=20),
        ),
    ]
