# Generated by Django 5.0.1 on 2025-06-17 03:06

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patient_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD'),
        ),
    ]
