# Generated by Django 5.0.1 on 2025-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_alter_drugs_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugs',
            name='DAR',
        ),
        migrations.AlterField(
            model_name='drugs',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
