# Generated by Django 5.0.1 on 2025-05-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_remove_drugs_dar_alter_drugs_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugs',
            options={'ordering': ['name', 'strength']},
        ),
    ]
