# Generated by Django 5.0.1 on 2025-05-12 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_alter_drugs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugs',
            options={'ordering': ['use_for']},
        ),
    ]
