# Generated by Django 5.0.1 on 2025-06-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precription', '0002_alter_prescription_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
