# Generated by Django 5.0.1 on 2025-06-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precription', '0003_prescription_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='bg_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='bg_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='blood',
            field=models.CharField(default='A+', max_length=3),
        ),
        migrations.AddField(
            model_name='prescription',
            name='bp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
