# Generated by Django 5.0.1 on 2025-06-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_alter_appointmentsession_options'),
        ('precription', '0004_prescription_bg_after_prescription_bg_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointment.patient_appointment'),
        ),
    ]
