# Generated by Django 5.0.1 on 2025-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], default='patient', max_length=10),
        ),
    ]
