# Generated by Django 5.0.1 on 2025-05-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('specialty', models.CharField(max_length=40)),
                ('degrees', models.CharField(max_length=40)),
                ('qualification', models.TextField()),
                ('chamber_address', models.TextField()),
                ('contact', models.CharField(max_length=11)),
                ('hospital_name', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='doctor_signatures/')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('working_hours', models.TextField()),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
