# Generated by Django 5.0.1 on 2025-05-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='registration_no',
            field=models.CharField(max_length=100),
        ),
    ]
