# Generated by Django 5.0.1 on 2025-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='degrees',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
