# Generated by Django 5.0.1 on 2025-05-23 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_doctor_degrees_alter_doctor_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
    ]
