# Generated by Django 5.0.1 on 2025-05-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_remove_doctor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='chamber_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
