# Generated by Django 5.0.1 on 2025-05-31 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctor_chamber_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-experience_years']},
        ),
    ]
