# Generated by Django 5.0.1 on 2025-06-22 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_remove_doctor_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=40)),
                ('qualification', models.CharField(max_length=200)),
                ('chamber_address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=11)),
                ('hospital_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
