# Generated by Django 5.0.1 on 2025-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_doctorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='first_name',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='last_name',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
