# Generated by Django 5.0.1 on 2025-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_doctorapplication_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='registration_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorapplication',
            name='registration_no',
            field=models.CharField(max_length=20),
        ),
    ]
